### PR TITLE
Retrained network.

### PR DESCRIPTION
**Pull request by felicepantaleo**
Update the energy regression and pid DNN.
Results were shown in Reco Meeting:
https://indico.cern.ch/event/1187388/contributions/4989483/attachments/2490125/4276212/TICLv4_RECO_Meeting_5Aug2022.pdf

To be tested together with an upcoming PR in cmssw.

### CODE REVIEW

**Comment by felicepantaleo** [comment]
@waredjeb @rovere  fyi

**Comment by felicepantaleo** [comment]
@cmsbuild please test with https://github.com/cms-sw/cmssw/pull/39302

**Comment by felicepantaleo** [comment]
@perrotta are the tests executed here the same as https://github.com/cms-sw/cmssw/pull/39302#issuecomment-1236895960 ?

**Comment by perrotta** [comment]
> @perrotta are the tests executed here the same as [cms-sw/cmssw#39302 (comment)](https://github.com/cms-sw/cmssw/pull/39302#issuecomment-1236895960) ?

Yes, even if based on a different IB and with a different list of accompanying PRs tested together
The RelVal Input failures notified here do not depend on the tested PR, and are also presented sporadically in other PR tests

**Comment by AdrianoDee** [comment]
@cmsbuild please test with https://github.com/cms-sw/cmssw/pull/39302

**Comment by AdrianoDee** [comment]
+upgrade
- see https://github.com/cms-sw/cmssw/pull/39302#issuecomment-1250732593

**Comment by clacaputo** [comment]
+reconstruction

**Comment by perrotta** [comment]
+1
- To be merged together with https://github.com/cms-sw/cmssw/pull/39302

**Comment by perrotta** [comment]
merge

**Pull request merged**
