### PR TITLE
Retrained particle ID model and energy regression for HLT TDR

### PR DESCRIPTION
**Pull request by rovere**
The machine learning model for particle ID and energy regression has
been retrained using the HLT TDR samples and a more recent version of
the TICL reconstruction and iterations (CMSSW_11_1_X). The model has not
been changed, but the full data-processing and training have been ported
to TF 2.1. The input and output layout and names are kept the same for
backward compatibility reasons.

### CODE REVIEW

**Comment by fwyzard** [comment]
@smuzaffar how do we propagate this to CMSSW ?
do we need a new tag for this package after merging the changes ?

**Comment by smuzaffar** [comment]
@fwyzard , is there any cmssw pr to test/use this new data file? If yes then you can already start the test using `test with cms-data/RecoHGCal-TICL#2` command

**Comment by fwyzard** [comment]
No, the change is supposed to be transparent for CMSSW.
Can we run the test here ?
Otherwise we can make an empty PR just for running the test.

**Comment by smuzaffar** [comment]
yes you can start the test here

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
> yes you can start the test here

perfect, thanks !

**Comment by slava77** [comment]
perhaps some update in README.md is necessary.

**Comment by slava77** [comment]
there are some changes in ticl-related plots; the regular object kinematic variables are roughly unchanged, but things related to ID and energy regression change quite substantially

id_probabilities distributions changed in range and shape
all_OldVSNew_TTbar14TeV2026D49PUwPRMXwf23434p999c_ticlTracksters_ticlTrackstersEM__RECO_obj_id_probabilities0

regressed_energy variables changed quite significantly
all_OldVSNew_TTbar14TeV2026D49PUwPRMXwf23434p999c_log10ticlTracksters_ticlTrackstersTrk__RECO_obj_regressed_energy

all_OldVSNew_TTbar14TeV2026D49PUwPRMXwf23434p999c_log10ticlTracksters_ticlTrackstersEM__RECO_obj_regressed_energy

are these expected?


@rovere 
for better PR documentation, please add a link to some slides or details of performance changes introduced by this PR.
Thank you.

**Comment by slava77** [comment]
I guess the most notable change in id_probabilities is that all muon ID probs are at 0 now
all_OldVSNew_TTbar14TeV2026D49PUwPRMXwf23434p999c_ticlTracksters_ticlTrackstersMerge__RECO_obj_id_probabilities2

**Comment by srimanob** [comment]
@rovere 
Any follow up on what to be expected from this PR? Thanks very much.

**Comment by fwyzard** [comment]
Needed for the HLT TDR studies, please merge ASAP.

**Comment by smuzaffar** [comment]
+externals

**Comment by rovere** [comment]
> I guess the most notable change in id_probabilities is that all muon ID probs are at 0 now
> all_OldVSNew_TTbar14TeV2026D49PUwPRMXwf23434p999c_ticlTracksters_ticlTrackstersMerge__RECO_obj_id_probabilities2

Ciao @slava77 , all, thanks for the detailed checks. Let me comment further:

* muons have been removed from the training and removed also from TICL reconstruction (temporarily, of course). It is therefore ok to have that category at 0 always.
* the energy regression is expected to significantly change. It was trained long ago with a rather different TICL configuration. The current performance, at least in 0PU, is better wrt to the old one. Nevertheless, it is still not recommended to use it. In this regard, those changes will not affect anything in the downstream reconstruction.
* An overall view of the performance  of the new model can be found [here](https://rovere.web.cern.ch/rovere/HGCAL/PID_ER/)
* Various POGs have been using this model (in the context of the HLT TDR preparation) since mid-summer last year: in this regard, its introduction should make their life easier.

**Comment by slava77** [comment]
+1

after the most recent clarifications from @rovere

**Comment by slava77** [comment]
@fwyzard @rovere 
for backports, is this  needed in 11_1_X or also in 11_2_X?

**Comment by fwyzard** [comment]
Yes, 11_1_X for the TDR studies.

**Comment by srimanob** [comment]
+Upgrade

**Comment by smuzaffar** [comment]
FYI @fwyzard
- https://github.com/cms-sw/cmsdist/pull/6562 : for 11.3.X . I will integrate it before 11h00 IB today
- https://github.com/cms-sw/cmsdist/pull/6563 : For 11.1.X

Should this go in 11.2.X too ( better to keep 11.2.X in sync) ?

**Comment by slava77** [comment]
> FYI @fwyzard
> 
>     * [cms-sw/cmsdist#6562](https://github.com/cms-sw/cmsdist/pull/6562) : for 11.3.X . I will integrate it before 11h00 IB today
> 
>     * [cms-sw/cmsdist#6563](https://github.com/cms-sw/cmsdist/pull/6563) : For 11.1.X
> 
> 
> Should this go in 11.2.X too ( better to keep 11.2.X in sync) ?

this PR changes physics results in the default reco.
- 11.1.X and 11.3.X are open for changes and the inclusion is straightforward.
- 11.2.X is closed (well, kind of); I guess a backport PR can be made, but it will have to be discussed in the ORP or PPD before merging.

**Comment by fwyzard** [comment]
From the HLT side there is no need to backport it to 11.2.x.

**Comment by rovere** [comment]
From the `HGCAL` point of view, it would be nice to have consistency between the releases.
On the other hand, `11_2` will not be used as a production release and having the updated model in `11_3` and `11_1` is far more important.

**Comment by jpata** [comment]
Note, we think this might have increased the memory consumption of step3 quite a bit (3865 -> 4345  MB):
https://jiwoong.web.cern.ch/jiwoong/results/phase2/summary_11_3_0/Summary_step3.html

TrackstersProducer::produce goes up by ~100MB.
pre1: https://jiwoong.web.cern.ch/jiwoong/cgi-bin/igprof-navigator/CMSSW_11_3_0_pre1/igprof_new_step3/ig.50/16
pre2: https://jiwoong.web.cern.ch/jiwoong/cgi-bin/igprof-navigator/CMSSW_11_3_0_pre2/igprof_new_step3/ig.50/16

The .pb model here is ~12MB!

**Comment by rovere** [comment]
@jpata thanks for reporting. We will try to investigate if and what could be done to improve the memory footprint.

**Comment by slava77** [comment]
there is also a larger increase during the module creation, all coming from the TF session
https://jiwoong.web.cern.ch/jiwoong/cgi-bin/igprof-navigator/CMSSW_11_3_0_pre1/igprof_new_step3/ig.1/235
vs 
https://jiwoong.web.cern.ch/jiwoong/cgi-bin/igprof-navigator/CMSSW_11_3_0_pre2/igprof_new_step3/ig.1/78
+240MB from a combination.

**Comment by slava77** [comment]
IIUC, the TF session is still one per thread. If we really have to have these huge memory use, it's time to move to a single session shared across all modules using the same model.

**Comment by fwyzard** [comment]
How lucky we are that CMS has set up a ML group, that can take care of fixing this problems !

**Comment by slava77** [comment]
When approving this PR I did not think of requesting a profiling run, we'd probably catch it sooner.
Somehow an increase of 12MB  in the model file did not suggest that it will lead to 240MB increment in the session size. A part of it is due to multiple instances of the same session in different producers.

Something to remember to do for the future to request `enable profiling`.

**Comment by slava77** [comment]
one obvious piece is HFNose algo which is created together with the no-nose variant in TrackstersProducer. Aren't these mutually exclusive?

**Comment by slava77** [comment]
I created https://github.com/cms-sw/cmssw/issues/32756 to follow up on the memory increase problem

**Pull request merged**
