### PR TITLE
New ONNX models for PID and Energy Regression 

### PR DESCRIPTION
**Pull request by Moanwar**
Adding the CNN models trained based on TICLv5 reconstruction information using a simple CNN-based approach. Two models were trained separately: one for trackster energy regression and one for particle ID, applied in different reconstruction steps—CLU3D (pattern recognition) and trackster linking. These models are saved in ONNX format for time optimization.

### CODE REVIEW

**Comment by mandrenguyen** [comment]
@cms-sw/reconstruction-l2  @cms-sw/upgrade-l2 
Please sign this PR, since you signed the one that consumes this data here:
https://github.com/cms-sw/cmssw/pull/45821

**Comment by Moanwar** [comment]
+Upgrade

**Comment by antoniovilela** [comment]
+1

**Comment by antoniovilela** [comment]
merge

**Pull request merged**
