### PR TITLE
Initial commit with CNN-based energy regression and ID tf model.

### PR DESCRIPTION
**Pull request by riga**
This PR adds an initial tensorflow model for energy regression and particle identification that is used in the HGCal reconstruction. The model is described in detail in this [talk](https://indico.cern.ch/event/799486/contributions/3492052/subcontributions/284302/attachments/1875750/3088524/MLforTICL_Scrum.pdf) given at the last [Patatrack Hackathon](https://indico.cern.ch/event/799486).

In addition, I added a few links to the README for easy navigation.

Edit: The cms-sw/cmssw PR for this is https://github.com/cms-sw/cmssw/pull/27917.

### CODE REVIEW

**Comment by slava77** [comment]
@riga 
is there a cms-sw/cmssw PR for this?

**Comment by riga** [comment]
@slava77 I will open the PR within the next 90 minutes.

**Comment by felicepantaleo** [comment]
@rovere fyi

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
+externals

**Comment by fabiocos** [comment]
@perrotta @kpedro88 as you have signed cms-sw/cmssw#27917 I assume you approve this PR as well (in any case it only adds new files, it does not modify anything already existing)

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by smuzaffar** [comment]
+externals

**Comment by kpedro88** [comment]
+upgrade

**Pull request merged**
