### PR TITLE
Simplified model to reduce live memory usage

### PR DESCRIPTION
**Pull request by rovere**
This is a simplified version of the model to perform PID and Energy Regression.
Preliminary tests on single particles sample show ~no sign of performance degradation.

Additional tests, especially to understand if the memory is under control, should be run.

### CODE REVIEW

**Comment by jpata** [comment]
enable profiling

**Comment by jpata** [comment]
@cmsbuild please test

**Comment by rovere** [comment]
@jpata for my education: does `please test` in this context/repository have the same meaning as in `cmssw`?

**Comment by jpata** [comment]
My understanding from previous attempts (e.g. https://github.com/cms-data/RecoHGCal-TICL/pull/2#issuecomment-761052075) is that it works like one would expect, thanks to the efforts of the core team (Shahzad)!

**Comment by rovere** [comment]
Ageing effects...
Very good, thanks for the reminder.

**Comment by rovere** [comment]
It seems to me that the baseline used 10 events, while the current test used 20. That's why cumulative numbers are doubled.
I saw no igprof report about memory usage.

**Comment by jpata** [comment]
@rovere I checked the workflow 23234.0 and both seem to use 10 events, where did you see this problem?
- baseline, [step1.log](https://cmssdt.cern.ch/SDT/jenkins-artifacts/ib-baseline-tests/CMSSW_11_3_X_2021-03-26-1100/slc7_amd64_gcc900/-GenuineIntel/matrix-results/23234.0_TTbar_14TeV+2026D49+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal/step1_TTbar_14TeV+2026D49+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal.log)
- this PR, [step1.log](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-fdc99c/13795/runTheMatrix-results/23234.0_TTbar_14TeV+2026D49+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal/step1_TTbar_14TeV+2026D49+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal.log)

As far as I can tell, the differences in the test outputs are meaningful and pick up the new model, [all_OldVSNew_TTbar14TeV2026D49wf23234p0c_ticlTracksters_ticlTrackstersMerge__RECO_obj_id_probabilities4.png](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_3_X_2021-03-26-1100+fdc99c/41914/validateJR/all_OldVSNew_TTbar14TeV2026D49wf23234p0/all_OldVSNew_TTbar14TeV2026D49wf23234p0c_ticlTracksters_ticlTrackstersMerge__RECO_obj_id_probabilities4.png):
image

Do the physics plots look fine from the HGCAL perspective?

It looks like profiling does not run the detailed memory comparison, but we can see a ~400MB/15% reduction, consistent with the previous increase (note this scales linearly with the number of threads given that the TF model is not shared in the ES).

- baseline, [JobReport3.xml](https://cmssdt.cern.ch/SDT/jenkins-artifacts/ib-baseline-tests/CMSSW_11_3_X_2021-03-26-1100/slc7_amd64_gcc900/-GenuineIntel/matrix-results/23234.0_TTbar_14TeV+2026D49+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal/JobReport3.xml)
```<Metric Name="PeakValueRss" Value="3686.95"/>```
- this PR, [JobReport3.xml](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-fdc99c/13795/runTheMatrix-results/23234.0_TTbar_14TeV+2026D49+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal/JobReport3.xml)
```<Metric Name="PeakValueRss" Value="3281.33"/>```

**Comment by rovere** [comment]
> @rovere I checked the workflow 23234.0 and both seem to use 10 events, where did you see this problem?

igprof results: the baseline uses 10 events, while this PR has been tested using 20. Therefore the cumulative time doubled. 

> 
> * baseline, [step1.log](https://cmssdt.cern.ch/SDT/jenkins-artifacts/ib-baseline-tests/CMSSW_11_3_X_2021-03-26-1100/slc7_amd64_gcc900/-GenuineIntel/matrix-results/23234.0_TTbar_14TeV+2026D49+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal/step1_TTbar_14TeV+2026D49+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal.log)
> * this PR, [step1.log](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-fdc99c/13795/runTheMatrix-results/23234.0_TTbar_14TeV+2026D49+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal/step1_TTbar_14TeV+2026D49+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal.log)
> 
> As far as I can tell, the differences in the test outputs are meaningful and pick up the new model, [all_OldVSNew_TTbar14TeV2026D49wf23234p0c_ticlTracksters_ticlTrackstersMerge__RECO_obj_id_probabilities4.png](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_3_X_2021-03-26-1100+fdc99c/41914/validateJR/all_OldVSNew_TTbar14TeV2026D49wf23234p0/all_OldVSNew_TTbar14TeV2026D49wf23234p0c_ticlTracksters_ticlTrackstersMerge__RECO_obj_id_probabilities4.png):
> image
> 
> Do the physics plots look fine from the HGCAL perspective?
> 
> It looks like profiling does not run the detailed memory comparison, but we can see a ~400MB/15% reduction, consistent with the previous increase (note this scales linearly with the number of threads given that the TF model is not shared in the ES).
> 
> * baseline, [JobReport3.xml](https://cmssdt.cern.ch/SDT/jenkins-artifacts/ib-baseline-tests/CMSSW_11_3_X_2021-03-26-1100/slc7_amd64_gcc900/-GenuineIntel/matrix-results/23234.0_TTbar_14TeV+2026D49+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal/JobReport3.xml)
>   `<Metric Name="PeakValueRss" Value="3686.95"/>`
> * this PR, [JobReport3.xml](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-fdc99c/13795/runTheMatrix-results/23234.0_TTbar_14TeV+2026D49+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal/JobReport3.xml)
>   `<Metric Name="PeakValueRss" Value="3281.33"/>`

I'd say difficult to judge. Since these are the only differences, I'd say we should be on the safe side.

**Comment by jpata** [comment]
Here's the memory consumption in 23434.21 with 8 threads, 100 events in pre5.
```
baseline, without this PR: Max VSIZ 29887.8 on evt 87 ; max RSS 16510.4 on evt 67
with this PR: Max VSIZ 27141.8 on evt 90 ; max RSS 13804.8 on evt 3
```
So it's back under thresholds and fixes https://github.com/cms-sw/cmssw/issues/32756.

**Comment by jpata** [comment]
+reconstruction
- fixes the large memory increase observed in cms-sw/cmssw#32756 and introduced in https://github.com/cms-data/RecoHGCal-TICL/pull/2
- no other reco changes besides in the TICL outputs

**Comment by smuzaffar** [comment]
+externals

**Comment by srimanob** [comment]
+Upgrade

**Comment by silviodonato** [comment]
> Here's the memory consumption in 23434.21 with 8 threads, 100 events in pre5.
> 
> ```
> baseline, without this PR: Max VSIZ 29887.8 on evt 87 ; max RSS 16510.4 on evt 67
> with this PR: Max VSIZ 27141.8 on evt 90 ; max RSS 13804.8 on evt 3
> ```
> 
> So it's back under thresholds and fixes [cms-sw/cmssw#32756](https://github.com/cms-sw/cmssw/issues/32756).

Very good news. https://github.com/cms-sw/cmsdist/pull/6769 is merged, so this PR will be included starting from this morning IB

**Pull request merged**
